[2024-12-04T19:16:43.142+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T19:16:43.158+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.extract manual__2024-12-04T19:16:40.068179+00:00 [queued]>
[2024-12-04T19:16:43.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.extract manual__2024-12-04T19:16:40.068179+00:00 [queued]>
[2024-12-04T19:16:43.163+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T19:16:43.172+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-12-04 19:16:40.068179+00:00
[2024-12-04T19:16:43.184+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T19:16:43.185+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2024-12-04T19:16:43.186+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_client_activity_EFIMOVICH_EVGENII', 'extract', 'manual__2024-12-04T19:16:40.068179+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_client_activity.py', '--cfg-path', '/tmp/tmphtdik83m']
[2024-12-04T19:16:43.187+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract
[2024-12-04T19:16:43.621+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.extract manual__2024-12-04T19:16:40.068179+00:00 [running]> on host fbfc88a57984
[2024-12-04T19:16:43.729+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_client_activity_EFIMOVICH_EVGENII' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T19:16:40.068179+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T19:16:40.068179+00:00'
[2024-12-04T19:16:43.729+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T19:16:43.730+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T19:16:43.730+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-12-04 19:16:43.158502+00:00
[2024-12-04T19:16:43.730+0000] {logging_mixin.py:190} INFO - Dag name:etl_client_activity_EFIMOVICH_EVGENII and current dag run status:running
[2024-12-04T19:16:43.730+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T19:16:43.731+0000] {logging_mixin.py:190} INFO - /opt/***
[2024-12-04T19:16:43.731+0000] {logging_mixin.py:190} INFO - /opt/***/dags/etl_client_activity.py
[2024-12-04T19:16:43.732+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 15, in extract_data
    profit_table = pd.read_csv('profit_table.csv')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'profit_table.csv'
[2024-12-04T19:16:43.748+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-04T19:16:43.749+0000] {logging_mixin.py:190} INFO - Task start:2024-12-04 19:16:43.158502+00:00 end:2024-12-04 19:16:43.748368+00:00 duration:0.589866
[2024-12-04T19:16:43.750+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: etl_client_activity_EFIMOVICH_EVGENII> dagrun:<DagRun etl_client_activity_EFIMOVICH_EVGENII @ 2024-12-04 19:16:40.068179+00:00: manual__2024-12-04T19:16:40.068179+00:00, state:running, queued_at: 2024-12-04 19:16:40.107814+00:00. externally triggered: True>
[2024-12-04T19:16:43.750+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'profit_table.csv'
[2024-12-04T19:16:43.751+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_client_activity_EFIMOVICH_EVGENII, task_id=extract, run_id=manual__2024-12-04T19:16:40.068179+00:00, execution_date=20241204T191640, start_date=20241204T191643, end_date=20241204T191643
[2024-12-04T19:16:43.779+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T19:16:43.780+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task extract ([Errno 2] No such file or directory: 'profit_table.csv'; 81)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 15, in extract_data
    profit_table = pd.read_csv('profit_table.csv')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'profit_table.csv'
[2024-12-04T19:16:43.827+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T19:16:44.104+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T19:16:44.106+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
