[2024-12-04T19:55:58.553+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T19:55:58.563+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform manual__2024-12-04T19:42:11.252169+00:00 [queued]>
[2024-12-04T19:55:58.566+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform manual__2024-12-04T19:42:11.252169+00:00 [queued]>
[2024-12-04T19:55:58.567+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-04T19:55:58.704+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2024-12-04 19:42:11.252169+00:00
[2024-12-04T19:55:58.713+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T19:55:58.714+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2024-12-04T19:55:58.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_client_activity_EFIMOVICH_EVGENII', 'transform', 'manual__2024-12-04T19:42:11.252169+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_client_activity.py', '--cfg-path', '/tmp/tmppdn0xp4n']
[2024-12-04T19:55:58.715+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask transform
[2024-12-04T19:55:58.755+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform manual__2024-12-04T19:42:11.252169+00:00 [running]> on host fbfc88a57984
[2024-12-04T19:55:58.831+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_client_activity_EFIMOVICH_EVGENII' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T19:42:11.252169+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T19:42:11.252169+00:00'
[2024-12-04T19:55:58.832+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T19:55:58.832+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T19:55:58.832+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-12-04 19:55:58.563554+00:00
[2024-12-04T19:55:58.832+0000] {logging_mixin.py:190} INFO - Dag name:etl_client_activity_EFIMOVICH_EVGENII and current dag run status:running
[2024-12-04T19:55:58.832+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T19:55:59.785+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 29, in transform_data
    transformed_data = transfrom(profit_table)  # Обрабатываем данные
                       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transfrom() missing 1 required positional argument: 'date'
[2024-12-04T19:55:59.876+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-04T19:55:59.878+0000] {logging_mixin.py:190} INFO - Task start:2024-12-04 19:55:58.563554+00:00 end:2024-12-04 19:55:59.869932+00:00 duration:1.306378
[2024-12-04T19:55:59.878+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: etl_client_activity_EFIMOVICH_EVGENII> dagrun:<DagRun etl_client_activity_EFIMOVICH_EVGENII @ 2024-12-04 19:42:11.252169+00:00: manual__2024-12-04T19:42:11.252169+00:00, state:running, queued_at: 2024-12-04 19:42:11.354231+00:00. externally triggered: True>
[2024-12-04T19:55:59.879+0000] {logging_mixin.py:190} INFO - Failure caused by transfrom() missing 1 required positional argument: 'date'
[2024-12-04T19:55:59.879+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_client_activity_EFIMOVICH_EVGENII, task_id=transform, run_id=manual__2024-12-04T19:42:11.252169+00:00, execution_date=20241204T194211, start_date=20241204T195558, end_date=20241204T195559
[2024-12-04T19:55:59.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T19:55:59.908+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task transform (transfrom() missing 1 required positional argument: 'date'; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 29, in transform_data
    transformed_data = transfrom(profit_table)  # Обрабатываем данные
                       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transfrom() missing 1 required positional argument: 'date'
[2024-12-04T19:55:59.993+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T19:56:00.048+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T19:56:00.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
