[2024-12-04T20:06:42.232+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T20:06:42.265+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform_d manual__2024-12-04T20:06:30.683774+00:00 [queued]>
[2024-12-04T20:06:42.285+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform_d manual__2024-12-04T20:06:30.683774+00:00 [queued]>
[2024-12-04T20:06:42.297+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T20:06:44.947+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_d> on 2024-12-04 20:06:30.683774+00:00
[2024-12-04T20:06:44.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T20:06:44.985+0000] {standard_task_runner.py:72} INFO - Started process 91 to run task
[2024-12-04T20:06:45.036+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_client_activity_EFIMOVICH_EVGENII', 'transform_d', 'manual__2024-12-04T20:06:30.683774+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_client_activity.py', '--cfg-path', '/tmp/tmpj5kyo5xk']
[2024-12-04T20:06:45.049+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask transform_d
[2024-12-04T20:06:45.428+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_client_activity_EFIMOVICH_EVGENII.transform_d manual__2024-12-04T20:06:30.683774+00:00 [running]> on host fbfc88a57984
[2024-12-04T20:06:46.066+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_client_activity_EFIMOVICH_EVGENII' AIRFLOW_CTX_TASK_ID='transform_d' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T20:06:30.683774+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T20:06:30.683774+00:00'
[2024-12-04T20:06:46.089+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T20:06:46.095+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T20:06:46.104+0000] {logging_mixin.py:190} INFO - Current task name:transform_d state:running start_date:2024-12-04 20:06:42.265480+00:00
[2024-12-04T20:06:46.105+0000] {logging_mixin.py:190} INFO - Dag name:etl_client_activity_EFIMOVICH_EVGENII and current dag run status:running
[2024-12-04T20:06:46.107+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T20:06:46.195+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 30, in transform_product_data
    filtered_table = profit_table[[f'sum_{product}', f'count_{product}']]  # Фильтруем данные по продукту
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['sum_d', 'count_d'], dtype='object')] are in the [columns]"
[2024-12-04T20:06:46.270+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-04T20:06:46.272+0000] {logging_mixin.py:190} INFO - Task start:2024-12-04 20:06:42.265480+00:00 end:2024-12-04 20:06:46.268225+00:00 duration:4.002745
[2024-12-04T20:06:46.273+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_d> dag:<DAG: etl_client_activity_EFIMOVICH_EVGENII> dagrun:<DagRun etl_client_activity_EFIMOVICH_EVGENII @ 2024-12-04 20:06:30.683774+00:00: manual__2024-12-04T20:06:30.683774+00:00, state:running, queued_at: 2024-12-04 20:06:30.728933+00:00. externally triggered: True>
[2024-12-04T20:06:46.275+0000] {logging_mixin.py:190} INFO - Failure caused by "None of [Index(['sum_d', 'count_d'], dtype='object')] are in the [columns]"
[2024-12-04T20:06:46.280+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_client_activity_EFIMOVICH_EVGENII, task_id=transform_d, run_id=manual__2024-12-04T20:06:30.683774+00:00, execution_date=20241204T200630, start_date=20241204T200642, end_date=20241204T200646
[2024-12-04T20:06:46.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T20:06:46.376+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task transform_d ("None of [Index(['sum_d', 'count_d'], dtype='object')] are in the [columns]"; 91)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_client_activity.py", line 30, in transform_product_data
    filtered_table = profit_table[[f'sum_{product}', f'count_{product}']]  # Фильтруем данные по продукту
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['sum_d', 'count_d'], dtype='object')] are in the [columns]"
[2024-12-04T20:06:46.425+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T20:06:46.473+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
